const mongoose = require('mongoose');
const preReqCSVFileSchema = mongoose.Schema({

  courseSubject: {type: String, required: true},
  courseCatalog: {type: String, required: true},

  courseTitle: {type: String, required: true},
  courseCredits: {type: String, required: true},
  componentCode: {type: String, required: true},
  preRequisiteDescription: {type: String, required: true},

  preReq1WC: {type: String, required: true},
  preReq1subject: {type: String, required: true},
  preReq1Category: {type: String, required: true},
  preReq2WC: {type: String, required: true},
  preReq2subject: {type: String, required: true},
  preReq2Category: {type: String, required: true},
  preReq3WC: {type: String, required: true},
  preReq3subject: {type: String, required: true},
  preReq3Category: {type: String, required: true},
  preReq4WC: {type: String, required: true},
  preReq4subject: {type: String, required: true},
  preReq4Category: {type: String, required: true},
  preReq5WC: {type: String, required: true},
  preReq5subject: {type: String, required: true},
  preReq5Category: {type: String, required: true},
  preReq6WC: {type: String, required: true},
  preReq6subject: {type: String, required: true},
  preReq6Category: {type: String, required: true},
  preReq7WC: {type: String, required: true},
  preReq7subject: {type: String, required: true},
  preReq7Category: {type: String, required: true},
  preReq8WC: {type: String, required: true},
  preReq8subject: {type: String, required: true},
  preReq8Category: {type: String, required: true},

  preReqORWC1: {type: String, required: true},
  preReqORsubject1: {type: String, required: true},
  preReqORCode1: {type: String, required: true},
  preReqORWC2: {type: String, required: true},
  preReqORsubject2: {type: String, required: true},
  preReqORCode2: {type: String, required: true},
  preReqORWC3: {type: String, required: true},
  preReqORsubject3: {type: String, required: true},
  preReqORCode3: {type: String, required: true},
  preReqORWC4: {type: String, required: true},
  preReqORsubject4: {type: String, required: true},
  preReqORCode4: {type: String, required: true},
  preReqORWC5: {type: String, required: true},
  preReqORsubject5: {type: String, required: true},
  preReqORCode5: {type: String, required: true},
  preReqORWC6: {type: String, required: true},
  preReqORsubject6: {type: String, required: true},
  preReqORCode6: {type: String, required: true},

  coReqWC1: {type: String, required: true},
  coReqSubject1: {type: String, required: true},
  coReqCategory1: {type: String, required: true},
  coReqWC2: {type: String, required: true},
  coReqSubject2: {type: String, required: true},
  coReqCategory2: {type: String, required: true},

  ntWC1: {type: String, required: true},
  ntSubject1: {type: String, required: true},
  ntCategory1: {type: String, required: true},
  ntWC2: {type: String, required: true},
  ntSubject2: {type: String, required: true},
  ntCategory2: {type: String, required: true},
  ntWC3: {type: String, required: true},
  ntSubject3: {type: String, required: true},
  ntCategory3: {type: String, required: true},
  ntWC4: {type: String, required: true},
  ntSubject4: {type: String, required: true},
  ntCategory4: {type: String, required: true},
  ntWC5: {type: String, required: true},
  ntSubject5: {type: String, required: true},
  ntCategory5: {type: String, required: true},
  ntWC6: {type: String, required: true},
  ntSubject6: {type: String, required: true},
  ntCategory6: {type: String, required: true},
  ntWC7: {type: String, required: true},
  ntSubject7: {type: String, required: true},
  ntCategory7: {type: String, required: true},
  ntWC8: {type: String, required: true},
  ntSubject8: {type: String, required: true},
  ntCategory8: {type: String, required: true},
  ntWC9: {type: String, required: true},
  ntSubject9: {type: String, required: true},
  ntCategory9: {type: String, required: true},
  ntWC10: {type: String, required: true},
  ntSubject10: {type: String, required: true},
  ntCategory10: {type: String, required: true},
  ntWC11: {type: String, required: true},
  ntSubject11: {type: String, required: true},
  ntCategory11: {type: String, required: true},
  ntWC12: {type: String, required: true},
  ntSubject12: {type: String, required: true},
  ntCategory12: {type: String, required: true}
});
module.exports = preReqCSVFileSchema;
